### ISSUE TITLE
Have some way to disable alerts from specific users

### ISSUE THREAD

**Issue by zestym3m3s** [AlessioDP/OreAnnouncer#100]
First suggestion is more important than the second.

I have another plugin on my server which lets players mine 3x3 squares, needless to say they find a lot of ores. I generally trust that they aren't cheating since they already have an expensive tool that speeds up mining, but I get MANY more alerts from them than players who are far more likely to be X-Raying like brand new players with nothing to lose. Is there any way to disable notifications for specific players? If there isn't, could there be a command to blacklist users from sending notifications like /oa blacklist <name>.

The next suggestion (for all I know this may already exist or be possible with luckperms) if it sounds like you've already made something for it please ignore this lol

I use multiverse which allows us to have multiple worlds on one server. One of those worlds is used for creative plots. Some players are clever and know about oreannouncer and mess with staff by spambreaking single blocks. Its kinda funny but only when its people who know when to stop. Having some way to turn off OA per world within the config would be nice. Again, this sounds like its probably already a thing and I haven't done much digging so if this exists please ignore this.

I like this plugin a lot, thanks for making it!

**Comment by AlessioDP** [comment]
I like the idea, I will try to implement the first thing :)

About the second, you can give `oreannouncer.admin.bypass.alerts`, `oreannouncer.admin.bypass.destroy` and `oreannouncer.admin.bypass.found` in these specific worlds to do not trigger alerts.

**Comment by AlessioDP** [comment]
Added whitelist support in 2.8.0 ;)

**Comment by zestym3m3s** [comment]
Thank you!
