### ISSUE TITLE
MCAntiMalware has detected a backdoor

### ISSUE THREAD

**Issue by stillerek** [AlessioDP/OreAnnouncer#101]
[AntiMalware] [10:53:16] [DETECTED]: File: plugins/OreAnnouncer/lib/com/h2database/h2/1.4.200/h2-1.4.200.jar MIGHT be infected with Spigot.MALWARE.SystemAccess.Process Class Path: org/h2/util/SourceCompiler

This is a bug?

**Comment by AlessioDP** [comment]
No,
the plugin downloads the official H2 jar to handle H2 databases. Try to ask to MCAntiMalware why it is considerated a malware.

**Comment by stillerek** [comment]
okey
