### ISSUE TITLE
2.4.1 issue with count (new feature)

### ISSUE THREAD

**Issue by arturek1666** [AlessioDP/OreAnnouncer#15]
The problem is that it says that it was find (amount) in (minutes) however it doesn't show like 50 diamonds was find in 5 minutes but instead it will say find 4 diamond in 10 minutes, But that's not really how many that player mined in that 10 minutes it just shows how many he mined now, with is confusing.

**Comment by AlessioDP** [comment]
Fixed with 2.4.2 ;)
