### ISSUE TITLE
NEW FEATURE : Synchronizing server settings in a BungeeCord architecture

### ISSUE THREAD

**Issue by Nogapra** [AlessioDP/OreAnnouncer#17]
Have the ability to name each server in a unique way in the config file 
e.g. : **ServerName: Survival**

This would allow for a new placeholder indicating the name of the server in the alert messages as **%server%**

At the same time, we could set up messages only in BungeeCord configuration files. 
There is a setting in the plugin configuration file in spigot:
bungeecord:
    enable: true
Which currently serves to run the spigot plugin with the same database as the BungeeCord and transmit the event detect on each server at BungeeCord this could also allow to disable the internal configuration files of each plugin on Spigot servers to use only bungee configuration files.

We may see a new permission to display the alerts that on the servers you want.
e.g. : **oreannoucer.server.[ServerName]** true/false

technically already possible thanks to LuckPerms and contextual management but not simple

**Comment by AlessioDP** [comment]
I like this idea, I will add this into my to-do list :)

**Comment by AlessioDP** [comment]
Implemented with 2.5.1 ;)
