### ISSUE TITLE
SilkSpawners hook

### ISSUE THREAD

**Issue by baticag** [AlessioDP/OreAnnouncer#28]
Spawners that are broken with SilkTouch from SilkSpawners plugin are not handled by this plugin.
Can you please add support and hook into it?

**Comment by AlessioDP** [comment]
Did you disable silk touch bypass in config.yml?

My plugin should be able to handle normal SPAWNER blocks.

**Comment by baticag** [comment]
Nope, it is same that is was before.
  # Do not count block broken with a silk touch tool
  bypass-silk-touch: false

But the problem is that SilkSpawners cancels block break event, and when you listen on MONITOR priority it is already cancelled.

**Comment by AlessioDP** [comment]
I understand, I have seen the code and I am able to hook into block break event.

But I don't see nothing related to event cancellation, it is cancelled only by the API event itself:
https://github.com/timbru31/SilkSpawners/blob/master/modules/SilkSpawners/src/main/java/de/dustplanet/silkspawners/listeners/SilkSpawnersBlockListener.java#L66

I can make a live test to be sure it works, another problem can be the wrong place of API event call, event if I listen to that event I am not sure that that one is gonna be cancelled later or not.

**Comment by baticag** [comment]
You are right, I made a mistake, it is not happening because it is cancelled.
Only thing I know for sure, that it was working fine on 2.3.2 and spawners were handled correctly.
We now updated to latest version from Spigot and got this problem.

**Comment by AlessioDP** [comment]
I tested it on OreAnnouncer v2.6.0 and it works:
1. I place a spawner block
2. With a silk touch pickaxe I destroy it
3. I drop the spawner and see in chat "AlessioDP found 1 spawner"

Maybe its a indirect fix with the new update :)
