### ISSUE TITLE
Cannot reload plugin

### ISSUE THREAD

**Issue by Bloodlex** [AlessioDP/OreAnnouncer#36]
`25.07 18:02:05 [Server] INFO Bloodlex issued server command: /oa reload
25.07 18:02:05 [Server] INFO [com.alessiodp.oreannouncer.libs.reflections.Reflections] Reflections took 1 ms to scan 1 urls, producing 1 keys and 1 values 
25.07 18:02:05 [Server] WARN java.util.concurrent.CompletionException: java.lang.RuntimeException: com.alessiodp.oreannouncer.libs.jdbi.v3.core.ConnectionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
25.07 18:02:05 [Server] WARN at java.util.concurrent.CompletableFuture.encodeThrowable(CompletableFuture.java:273)
25.07 18:02:05 [Server] WARN at java.util.concurrent.CompletableFuture.completeThrowable(CompletableFuture.java:280)
25.07 18:02:05 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1643)
25.07 18:02:05 [Server] WARN at java.util.concurrent.ThreadPoolExecutor.runWorker(ThreadPoolExecutor.java:1149)
25.07 18:02:05 [Server] WARN at java.util.concurrent.ThreadPoolExecutor$Worker.run(ThreadPoolExecutor.java:624)
25.07 18:02:05 [Server] WARN at java.lang.Thread.run(Thread.java:748)
25.07 18:02:05 [Server] WARN Caused by: java.lang.RuntimeException: com.alessiodp.oreannouncer.libs.jdbi.v3.core.ConnectionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.core.common.storage.dispatchers.SQLDispatcher.init(SQLDispatcher.java:59)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.core.common.storage.DatabaseManager.init(DatabaseManager.java:47)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.core.common.storage.DatabaseManager.reload(DatabaseManager.java:80)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.common.OreAnnouncerPlugin.reloadConfiguration(OreAnnouncerPlugin.java:81)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.common.commands.sub.CommandReload.onCommand(CommandReload.java:67)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.core.common.commands.utils.CommandUtils.lambda$executeCommand$0(CommandUtils.java:40)
25.07 18:02:05 [Server] WARN at java.util.concurrent.CompletableFuture$AsyncRun.run(CompletableFuture.java:1640)
25.07 18:02:05 [Server] WARN ... 3 more
25.07 18:02:05 [Server] WARN Caused by: com.alessiodp.oreannouncer.libs.jdbi.v3.core.ConnectionException: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.libs.jdbi.v3.core.Jdbi.open(Jdbi.java:318)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.libs.jdbi.v3.core.Jdbi.withHandle(Jdbi.java:339)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.libs.jdbi.v3.core.Jdbi.useHandle(Jdbi.java:357)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.libs.jdbi.v3.core.Jdbi.useTransaction(Jdbi.java:390)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.core.common.storage.sql.migrator.Migrator.migrate(Migrator.java:67)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.core.common.storage.dispatchers.SQLDispatcher.migrateTables(SQLDispatcher.java:92)
25.07 18:02:05 [Server] WARN at com.alessiodp.oreannouncer.core.common.storage.dispatchers.SQLDispatcher.init(SQLDispatcher.java:57)
25.07 18:02:05 [Server] WARN ... 9 more
25.07 18:02:05 [Server] WARN Caused by: org.h2.jdbc.JdbcSQLNonTransientConnectionException: Database may be already in use: null. Possible solutions: close all other connection(s); use the server mode [90020-200]
25.07 18:02:05 [Server] WARN at org.h2.message.DbException.getJdbcSQLException(DbException.java:622)
25.07 18:02:05 [Server] WARN at org.h2.message.DbException.getJdbcSQLException(DbException.java:429)`

**Comment by AlessioDP** [comment]
Can I have the server log? I have to know how the plugin loaded at the start of the server, or directly do a /reload (or restart) and see if its working.

**Comment by Bloodlex** [comment]
Hey, of course :) Here you have a more complex example with steps:
1. /oa reload
2. restart
3. again /oa reload try

Unfortunately it doesn't work :( Could you please help? Thank you very much.

More complete log here:
[https://pastebin.com/njEatVcm](https://pastebin.com/njEatVcm)

**Comment by AlessioDP** [comment]
Unfortunately I think its something I cannot fix, the error is clear `Database may be already in use`.

Maybe Multicraft opens the database once its created and it stops to work (?)
You can try to change the database to SQLite or download the server locally and see if it works on your computer.

**Comment by Bloodlex** [comment]
I have no idea, but after changing to SQLite it works as it should ;) Thanks a lot ^^
