### ISSUE TITLE
Plugin won't start after update to 2.7.0

### ISSUE THREAD

**Issue by Bloodlex** [AlessioDP/OreAnnouncer#39]
Seems like changing the version SQLite is the problem :(

I have to use SQLite, because H2 didn't work for me.

`30.07 09:14:11 [Server] INFO [OreAnnouncer] Initializing OreAnnouncer 2.7.0
30.07 09:14:11 [Server] WARN [OreAnnouncer] The configuration key 'blocks.itemmods.enable' in 'config.yml' was not found, configuration outdated?
30.07 09:14:11 [Server] WARN [OreAnnouncer] The configuration key 'blocks.mmoitems.enable' in 'config.yml' was not found, configuration outdated?
30.07 09:14:11 [Server] WARN [OreAnnouncer] The file config.yml is outdated!
30.07 09:14:12 [Server] INFO [OreAnnouncer] Downloaded library https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.32.3.2/sqlite-jdbc-3.32.3.2.jar
30.07 09:14:12 [Server] WARN [OreAnnouncer] *** INVALID CHECKSUM ***
30.07 09:14:12 [Server] WARN [OreAnnouncer]  Library :  org.xerial:sqlite-jdbc:3.32.3.2
30.07 09:14:12 [Server] WARN [OreAnnouncer]  URL :  https://repo1.maven.org/maven2/org/xerial/sqlite-jdbc/3.32.3.2/sqlite-jdbc-3.32.3.2.jar
30.07 09:14:12 [Server] WARN [OreAnnouncer]  Expected :  xRv+M+D7Dcqs/CPs4+DuGoiAqx0mF2dpBMaUv8a3xcs=
30.07 09:14:12 [Server] WARN [OreAnnouncer]  Actual :  7CL07opEtcliARxo7Ocu5TeojrvnytcNP4fIFq6lM1c=
30.07 09:14:13 [Server] ERROR Error occurred while enabling OreAnnouncer v2.7.0 (Is it up to date?)
30.07 09:14:13 [Server] INFO java.lang.RuntimeException: Failed to download library 'org.xerial:sqlite-jdbc:3.32.3.2'
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.core.common.addons.external.libby.LibraryManager.downloadLibrary(LibraryManager.java:353) ~[?:?]
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.core.common.addons.external.libby.LibraryManager.loadLibrary(LibraryManager.java:413) ~[?:?]
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.core.common.addons.ADPLibraryManager.setupLibrariesForSQLite(ADPLibraryManager.java:67) ~[?:?]
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.core.common.storage.StorageType.initLibraries(StorageType.java:46) ~[?:?]
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.core.common.storage.DatabaseManager.init(DatabaseManager.java:35) ~[?:?]
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.core.common.storage.DatabaseManager.reload(DatabaseManager.java:80) ~[?:?]
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.common.OreAnnouncerPlugin.loadCore(OreAnnouncerPlugin.java:55) ~[?:?]
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.bukkit.BukkitOreAnnouncerPlugin.loadCore(BukkitOreAnnouncerPlugin.java:50) ~[?:?]
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.core.common.ADPPlugin.handle(ADPPlugin.java:117) ~[?:?]
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.core.common.ADPPlugin.enabling(ADPPlugin.java:60) ~[?:?]
30.07 09:14:13 [Server] INFO at com.alessiodp.oreannouncer.core.bukkit.bootstrap.ADPBukkitBootstrap.onEnable(ADPBukkitBootstrap.java:33) ~[?:?]
30.07 09:14:13 [Server] INFO at org.bukkit.plugin.java.JavaPlugin.setEnabled(JavaPlugin.java:263) ~[patched_1.15.2.jar:git-Paper-380]
30.07 09:14:13 [Server] INFO at org.bukkit.plugin.java.JavaPluginLoader.enablePlugin(JavaPluginLoader.java:380) ~[patched_1.15.2.jar:git-Paper-380]
30.07 09:14:13 [Server] INFO at org.bukkit.plugin.SimplePluginManager.enablePlugin(SimplePluginManager.java:483) ~[patched_1.15.2.jar:git-Paper-380]
30.07 09:14:13 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugin(CraftServer.java:472) ~[patched_1.15.2.jar:git-Paper-380]
30.07 09:14:13 [Server] INFO at org.bukkit.craftbukkit.v1_15_R1.CraftServer.enablePlugins(CraftServer.java:386) ~[patched_1.15.2.jar:git-Paper-380]
30.07 09:14:13 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.a(MinecraftServer.java:488) ~[patched_1.15.2.jar:git-Paper-380]
30.07 09:14:13 [Server] INFO at net.minecraft.server.v1_15_R1.DedicatedServer.init(DedicatedServer.java:298) ~[patched_1.15.2.jar:git-Paper-380]
30.07 09:14:13 [Server] INFO at net.minecraft.server.v1_15_R1.MinecraftServer.run(MinecraftServer.java:908) ~[patched_1.15.2.jar:git-Paper-380]
30.07 09:14:13 [Server] INFO at java.lang.Thread.run(Thread.java:748) [?:1.8.0_252]
30.07 09:14:13 [Server] INFO [OreAnnouncer] Disabling OreAnnouncer v2.7.0
30.07 09:14:13 [Server] INFO [OreAnnouncer] Disabling OreAnnouncer
30.07 09:14:13 [Server] INFO [OreAnnouncer] OreAnnouncer disabled`

**Comment by AlessioDP** [comment]
Fixed with OreAnnouncer 2.7.2 ;)
