### ISSUE TITLE
OreAnnouncer Issues 1.14+

### ISSUE THREAD

**Issue by iSkeptical** [AlessioDP/OreAnnouncer#4]
I have not tested pre-1.14... But I can tell you some issues I'm having with it in 1.14+
I'm on PaperSpigot for 1.14.2 when I created this thread, but I have noticed it since 1.14.
MySQL doesn't seem to be receiving the logs. The plugin generated the tables and everything... It's just after 2 weeks not a single log as been made to it.
As well as McMMO superbreaker seems to completely bypass OreAnnoucner. When players use superbreaker, it doesn't log anything nor  announce it to the admins.

**Comment by AlessioDP** [comment]
OreAnnouncer does not support 1.14 due to new async threads rules, I will update it as fast as I can :)

**Comment by iSkeptical** [comment]
Very understandable. A lot of people have the same issues. Just making sure you're aware. :)

**Comment by AlessioDP** [comment]
Added support for 1.14 with OA 2.2.0 ;)
