### ISSUE TITLE
SQLite Database locked exceptions

### ISSUE THREAD

**Issue by Bloodlex** [AlessioDP/OreAnnouncer#44]
Hello,

Unfortunately I have another issue 😢 It seems that SQLite database is often locked for some reason and many such exceptions show up in my console:

Version: Paper-380 (MC 1.15.2)
OreAnnouncer 2.7.2

[https://pastebin.com/NZhw2Eg3](https://pastebin.com/NZhw2Eg3)

**Comment by AlessioDP** [comment]
I will investigate, thank you :)

**Comment by Bloodlex** [comment]
Thanks! 👍

**Comment by Bloodlex** [comment]
I've already found out what the issue was: it was related to TitleManager plugin and too frequent updates on statistics leading to database connection overflow.

Thanks for your help! 👍
