### ISSUE TITLE
Config does not update between versions

### ISSUE THREAD

**Issue by OverlordFreddo** [AlessioDP/OreAnnouncer#46]
When updating from/to any version, the config does not update and the console nags me:
`[OreAnnouncer]: The configuration key 'blocks.itemmods.enable' in 'config.yml' was not found, configuration outdated?
[OreAnnouncer]: The configuration key 'blocks.mmoitems.enable' in 'config.yml' was not found, configuration outdated?
[OreAnnouncer]: The file config.yml is outdated!`

As I'm sure you're aware, other plugins update the config and update it automatically.  As I don't know if this is an intended part of OA, I do not know if this should be classed as a bug or enhancement.

It is worth noting that this also happens with LoginAPI.

**Comment by AlessioDP** [comment]
Is not a bug :)

Right now I do not wanna touch your configs at all, for security reasons!
I have in mind a way to auto update configs but I didn't try to develop it yet :S
If I develop it I will for sure implement it in all my plugins ;)
