### ISSUE TITLE
SilkTouch not showing in game alerts

### ISSUE THREAD

**Issue by SilencedSoppu** [AlessioDP/OreAnnouncer#56]
When a player mines ore using a silk touch pick or finds the ore it is not announced in game as an alert, it is niether shown in console as an alert as well. in order to combat xray this would be a useful addition to help catch and find them. if this issue has already been resolved i did not see it in past issue list. i was also noticing when using beds to mine in the nether those also do not show up in the alerts system.

**Comment by AlessioDP** [comment]
Did you set this option to false? https://github.com/AlessioDP/OreAnnouncer/blob/master/bukkit/src/main/resources/bukkit/config.yml#L175

About nether, it is not supported because its hard to get who destroyed the block with an explosion. I can try to implement bed explosion support like TNT :)

**Comment by SilencedSoppu** [comment]
i must of read through it to quickly, thats all my fault, the bed implemntation would be very useful, thank you for the quick reply!

**Comment by AlessioDP** [comment]
No problem ;)
