### ISSUE TITLE
Getting kicked everytime someone mines!!!!!!!

### ISSUE THREAD

**Issue by arturek1666** [AlessioDP/OreAnnouncer#72]
![image](https://user-images.githubusercontent.com/1558228/98438498-8cb06400-20e2-11eb-9ab6-db892acebc4f.png)
I use newest OA and I am getting kicked every time someone mines i even go as far as reset all config to default and language!!!!

**Comment by arturek1666** [comment]
looks like it's global issue hh.

**Comment by AlessioDP** [comment]
Just to be clear.
Its an issue with JSON parsing of the server, usually happens when using CraftBukkit instead of Spigot/PaperSpigot/...

**Comment by arturek1666** [comment]
I use Tuinity
