### ISSUE TITLE
Errors in IntelliJ IDEA

### ISSUE THREAD

**Issue by sasha066** [AlessioDP/OreAnnouncer#85]
Hello. I want to make some adjustments to the plugin, but when I try to import the sources into IntelliJ IDEA I get some errors in the code. For example, this:
![image](https://user-images.githubusercontent.com/71141771/106510611-d6d59580-64d7-11eb-9cfa-7a81a48c04fe.png)
Perhaps this is because IntelliJ cannot import a Maven modular project correctly. But I have never worked with Maven and therefore do not know how to fix it.

**Comment by AlessioDP** [comment]
OreAnnouncer uses Lombok, if you are using IntelliJ you must install the plugin + enable Annotation Processor in settings :)

**Comment by sasha066** [comment]
> OreAnnouncer uses Lombok, if you are using IntelliJ you must install the plugin + enable Annotation Processor in settings :)

Ah, here's the thing. :D
Thanks. I want to try and fix the DiscordSRV integration. If I succeed, I will create a Pull Request.

**Comment by AlessioDP** [comment]
I already made the fix in my local git, but I cannot push it because I am preparing a big update.

Feel free to use it for your server :)
