### ISSUE TITLE
CoreProtect Integration

### ISSUE THREAD

**Issue by ArcticRaven** [AlessioDP/OreAnnouncer#88]
Since CoreProtect already logs the information that OA is collecting as well - it would be nice to see a feature where it uses that data to query long-term lookups and comparisons. 

There's an old resource that used to do this and compare the data of %ores mined vs standard blocks like stone, andesite, etc. Instead of just checking for visual frequency in chat - this allows the comparison in a long term period. In application this style of hunting x-rayers proves effective as it relies on data and not potential false positives. General behavior indicates that most normal players will result in 0-4% diamond ore vs stone, and 0-12% iron ore, etc. When players exceed these certain limits there's a strong indicator that they are using an xray client. By being able to teleport to those locations - you can then verify based of mining trails if it was xray or not. 

Either way - just using CP logging would reduce how many loggers need to be happening at any time, and most servers are already using core protect to begin with.

**Comment by AlessioDP** [comment]
Someone already spoke with me about this feature but I discard it for some reasons:
- CoreProtect doesn't have a Maven repo
- CP is not open source (not required but useful for me to understand how to use it)
- Queries can be heavy to perform

Right now, with advanced count system, you can log blocks mined, any block (stone, cobblestone, ...) and make a ratio by yourself. The ratio calculation is not made by the plugin but in my todo list I have a new feature "block mining ratios", that would be useful to make these percentages.

**Comment by ArcticRaven** [comment]
I understand - Maven does absolutely make integration easier, however in this case I really do think that it should be considered for the reasons I stated prior. 

Its not very useful for servers to continue logging the same information repeatedly. And Database Queries are only has heavy as the Query being done. Generally servers query this kind of information at most a couple of times a day, and for the type of query this would be useful for, works better with longer pools of information. Most (experienced) Core Protect users do limit how much data they store - usually keeping 30 days or less information depending on the size of the server. Ultimate the weight of the query is up to the amount of information it has to query. 

 I think more servers would find this resource beneficial if it did at least try to work with their core resources and optimize where it can. However, given there are private development resources that do this functionality - I'll continue to invest in those.
 
 Thanks for the consideration!

**Comment by AlessioDP** [comment]
I understand!
I already knew how to reply because I actually tried to implement it but I just figured out that would be a lot better to make my own "database" of mined blocks.

Thanks to that I can make my own specific queries for every kind of operation.
