### ISSUE TITLE
[BUG] Plugin fails to load when using Java 16

### ISSUE THREAD

**Issue by Thornbush42** [AlessioDP/OreAnnouncer#93]
- **Versions**
Paper: #692
OreAnnouncer: 2.7.2
Java: 16

- **Describe the bug**
Plugin fails to start when using Java 16

- **Steps to reproduce the behavior**
Install and run Paper with Java 16, watch the plugin not be able to load.

- **Expected behavior**
Plugin loads as it should and has done using Java 11

- **Screenshots**
Console error: https://pastebin.com/TarwxcF2
config.yml: https://pastebin.com/f7t5TQXg
Log.txt is empty

**Comment by AlessioDP** [comment]
Java 16 is not supported due to impossibility in external library loading.

Let's wait for Bukkit API changes or new way to load external libraries ;)

Currently, supported versions are Java 8-15.

**Comment by Thornbush42** [comment]
I found a temporary workaround, add "--illegal-access=permit" as a start-up flag
fyi

**Comment by TNTUP** [comment]
Thats a shame, thats the only plugin that notifies me across on a bungee network :S and if anyone passes on 1.17.x this plugin would be unusuable
